### ISSUE TITLE
Bookmark icon hidden

### ISSUE THREAD

**Issue by alexkrolick** [nomiku/Tender-Issues#6]

**Comment by jumarochi** [comment]
is there a solution to.solve this??

**Comment by alexkrolick** [comment]
The icon was disabled on mobile. It is now accessible from the Recipe screen (see below).
![screen shot 2015-07-30 at 5 59 43 pm](https://cloud.githubusercontent.com/assets/1571667/8998631/d857fffa-36e4-11e5-9658-f468147df2e4.png)
