### ISSUE TITLE
cant see the up menu

### ISSUE THREAD

**Issue by jumarochi** [nomiku/Tender-Issues#9]
Cant see lhe menu on the upside of the app...
Then, cant acess the cookbook to Luke ir not the recipes.
im using a Sony smartphone.

**Comment by alexkrolick** [comment]
Is this resolved? I see you closed it. If not, what screen resolution is your phone?

**Comment by alexkrolick** [comment]
(was moved to #10 )

**Comment by jumarochi** [comment]
not solved, screen resolution 540x960 pixel
now cant see all the app, black screen when lauch the app

**Comment by alexkrolick** [comment]
See #1 for the black screen issue. It is related to the page needing to fully load before being displayed. On slow connections, this results in a black screen for a while.

I moved discussion of this bug to #10 because it is more specific.
